export const northpoleDailyOptionAbi = [
  {
    type: "function",
    name: "createOffer",
    stateMutability: "payable",
    inputs: [
      { name: "indexId", type: "bytes32" },
      { name: "areaId", type: "bytes32" },
      { name: "yyyymmdd", type: "uint32" },
      { name: "strike1e6", type: "int256" },
      { name: "direction", type: "uint8" },
      { name: "premiumWei", type: "uint256" },
      { name: "buyDeadline", type: "uint64" },
    ],
    outputs: [{ name: "offerId", type: "uint256" }],
  },
  {
    type: "function",
    name: "buy",
    stateMutability: "payable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "settle",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "offers",
    stateMutability: "view",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [
      { name: "seller", type: "address" },
      { name: "buyer", type: "address" },
      { name: "indexId", type: "bytes32" },
      { name: "areaId", type: "bytes32" },
      { name: "yyyymmdd", type: "uint32" },
      { name: "strike1e6", type: "int256" },
      { name: "direction", type: "uint8" },
      { name: "premiumWei", type: "uint256" },
      { name: "payoutWei", type: "uint256" },
      { name: "buyDeadline", type: "uint64" },
      { name: "cancelled", type: "bool" },
      { name: "settled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "nextOfferId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  // optional but nice for UI feeds:
  {
    type: "event",
    name: "OfferCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "offerId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: true, name: "indexId", type: "bytes32" },
      { indexed: false, name: "areaId", type: "bytes32" },
      { indexed: false, name: "yyyymmdd", type: "uint32" },
      { indexed: false, name: "strike1e6", type: "int256" },
      { indexed: false, name: "direction", type: "uint8" },
      { indexed: false, name: "premiumWei", type: "uint256" },
      { indexed: false, name: "payoutWei", type: "uint256" },
      { indexed: false, name: "buyDeadline", type: "uint64" },
    ],
  },
  { type: "event", name: "OfferPurchased", anonymous: false, inputs: [
    { indexed: true, name: "offerId", type: "uint256" },
    { indexed: true, name: "buyer", type: "address" },
  ]},
  { type: "event", name: "OfferCancelled", anonymous: false, inputs: [
    { indexed: true, name: "offerId", type: "uint256" },
  ]},
  { type: "event", name: "OfferSettled", anonymous: false, inputs: [
    { indexed: true, name: "offerId", type: "uint256" },
    { indexed: false, name: "winner", type: "address" },
    { indexed: false, name: "indexValue1e6", type: "int256" },
    { indexed: false, name: "datasetHash", type: "bytes32" },
    { indexed: false, name: "payoutWei", type: "uint256" },
  ]},
] as const;
