export const requestRegistryAbi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "fulfiller",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "consumer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "nextRequestId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "requests",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "indexId", type: "bytes32" },
      { name: "areaId", type: "bytes32" },
      { name: "yyyymmdd", type: "uint32" },
      { name: "currency", type: "string" },
      { name: "createdAt", type: "uint64" },
      { name: "status", type: "uint8" },
      { name: "value1e6", type: "int256" },
      { name: "datasetHash", type: "bytes32" },
      { name: "fulfilledAt", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "createRequest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "indexId", type: "bytes32" },
      { name: "areaId", type: "bytes32" },
      { name: "yyyymmdd", type: "uint32" },
      { name: "currency", type: "string" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    type: "function",
    name: "markFulfilled",
    stateMutability: "nonpayable",
    inputs: [
      { name: "requestId", type: "uint256" },
      { name: "value1e6", type: "int256" },
      { name: "datasetHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelRequest",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "RequestCreated",
    inputs: [
      { indexed: true, name: "requestId", type: "uint256" },
      { indexed: true, name: "indexId", type: "bytes32" },
      { indexed: true, name: "areaId", type: "bytes32" },
      { indexed: false, name: "yyyymmdd", type: "uint32" },
      { indexed: false, name: "currency", type: "string" },
      { indexed: false, name: "consumer", type: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestFulfilled",
    inputs: [
      { indexed: true, name: "requestId", type: "uint256" },
      { indexed: false, name: "value1e6", type: "int256" },
      { indexed: false, name: "datasetHash", type: "bytes32" },
      { indexed: false, name: "fulfilledAt", type: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestCancelled",
    inputs: [{ indexed: true, name: "requestId", type: "uint256" }],
    anonymous: false,
  },
] as const;
